from __future__ import annotations

import sqlite3
from datetime import date, datetime, timezone
from pathlib import Path

import pandas as pd

from config.settings import REPORTS_DIR

DISCLAIMER = (
    "This report is generated by an automated technical-analysis tool for "
    "research and educational purposes only. It is NOT investment advice. "
    "Past accuracy does not guarantee future performance. Consult a "
    "registered investment advisor before making financial decisions."
)

PHASE_LABEL = "Phase 1"
INDICATOR_VERSION = "v1"
PROMPT_VERSION = "v1"
DATA_PROVIDER = "yfinance"


def _dashboard_df(conn: sqlite3.Connection, run_date: str, universe_size: int, made: int, skipped: int) -> pd.DataFrame:
    accuracy = pd.read_sql_query("SELECT direction_correct, target_hit, pct_error FROM accuracy_evaluations", conn)
    direction_accuracy = accuracy["direction_correct"].mean() * 100 if not accuracy.empty else None
    target_hit_rate = accuracy["target_hit"].mean() * 100 if not accuracy.empty else None
    avg_error = accuracy["pct_error"].mean() if not accuracy.empty else None
    return pd.DataFrame([{
        "run_date": run_date,
        "universe_size": universe_size,
        "predictions_made": made,
        "predictions_skipped": skipped,
        "direction_accuracy_percent": direction_accuracy,
        "target_hit_rate_percent": target_hit_rate,
        "avg_error_percent": avg_error,
        "disclaimer": DISCLAIMER,
    }])


def _todays_predictions_df(conn: sqlite3.Connection, run_date: str) -> pd.DataFrame:
    return pd.read_sql_query(
        "SELECT symbol, horizon_days, direction, target_price, range_low, range_high, "
        "expected_move_percent, confidence, reasoning FROM predictions WHERE prediction_date = ? "
        "ORDER BY symbol, horizon_days", conn, params=(run_date,),
    )


def _prediction_history_df(conn: sqlite3.Connection) -> pd.DataFrame:
    return pd.read_sql_query("SELECT * FROM predictions ORDER BY prediction_date, symbol, horizon_days", conn)


def _accuracy_df(conn: sqlite3.Connection) -> pd.DataFrame:
    return pd.read_sql_query(
        "SELECT a.*, p.symbol, p.horizon_days, p.direction AS predicted_direction, p.confidence "
        "FROM accuracy_evaluations a JOIN predictions p ON p.id = a.prediction_id "
        "ORDER BY a.evaluation_date", conn,
    )


def _stock_performance_df(conn: sqlite3.Connection) -> pd.DataFrame:
    df = _accuracy_df(conn)
    if df.empty:
        return pd.DataFrame(columns=["symbol", "direction_accuracy_percent", "target_hit_rate_percent", "avg_pct_error", "n_evaluations"])
    grouped = df.groupby("symbol").agg(
        direction_accuracy_percent=("direction_correct", lambda s: s.mean() * 100),
        target_hit_rate_percent=("target_hit", lambda s: s.mean() * 100),
        avg_pct_error=("pct_error", "mean"),
        n_evaluations=("prediction_id", "count"),
    ).reset_index()
    return grouped


def _historical_prices_df(conn: sqlite3.Connection, symbols: list[str]) -> pd.DataFrame:
    if not symbols:
        return pd.DataFrame(columns=["symbol", "date", "open", "high", "low", "close", "adj_close", "volume"])
    placeholders = ",".join("?" for _ in symbols)
    return pd.read_sql_query(
        f"SELECT symbol, date, open, high, low, close, adj_close, volume FROM price_bars "
        f"WHERE symbol IN ({placeholders}) ORDER BY symbol, date", conn, params=symbols,
    )


def _news_sentiment_placeholder_df() -> pd.DataFrame:
    return pd.DataFrame(columns=["symbol", "headline", "sentiment_score", "source", "date"])


def _configuration_df(run_date: str) -> pd.DataFrame:
    return pd.DataFrame([{
        "universe_methodology": "Static NIFTY-50 weights, top 20 by weight",
        "indicator_score_version": INDICATOR_VERSION,
        "prompt_version": PROMPT_VERSION,
        "data_provider": DATA_PROVIDER,
        "generation_timestamp": datetime.now(timezone.utc).isoformat(),
        "phase": PHASE_LABEL,
        "run_date": run_date,
    }])


def generate_report(
    conn: sqlite3.Connection, run_date: date, symbols: list[str],
    predictions_made: int, predictions_skipped: int, output_dir: Path = REPORTS_DIR,
) -> Path:
    # Sheet named "News/Sentiment (placeholder)" in the spec is written as
    # "News-Sentiment" here because "/" is not a legal Excel sheet-name character.
    output_dir.mkdir(parents=True, exist_ok=True)
    run_date_str = run_date.isoformat()
    output_path = output_dir / f"{run_date_str}.xlsx"

    sheets = {
        "Dashboard": _dashboard_df(conn, run_date_str, len(symbols), predictions_made, predictions_skipped),
        "Today's Predictions": _todays_predictions_df(conn, run_date_str),
        "Prediction History": _prediction_history_df(conn),
        "Accuracy": _accuracy_df(conn),
        "Stock Performance": _stock_performance_df(conn),
        "Historical Prices": _historical_prices_df(conn, symbols),
        "News-Sentiment": _news_sentiment_placeholder_df(),
        "Configuration": _configuration_df(run_date_str),
    }

    with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
        for sheet_name, df in sheets.items():
            df.to_excel(writer, sheet_name=sheet_name[:31], index=False)

    return output_path
